### ISSUE TITLE
Tela de autenticação do sistema

### ISSUE THREAD

**Issue by lilialnas** [luanaflorencio/economico#1]
Eu como usuário do sistema desejo ter uma tela de autenticação do sistema para garantir que o sistema está sendo utilizado pelas minhas credencias garantido meu acesso e segurança nos dados.

- [x] Realizar protótipo de interface e interação (cenários de exceção devem ser projetados como: esqueci a senha, usuário e senha incorretos, campos preenchidos incorretamente etc.)
- [x] Definir mecanismo de autenticação
- [x] Criação do backend (com validações de tamanho, obrigatoriedade de campos, fluxos alternativos de autenticação também)
- [x] Criação do frontend (máscara de preenchimento dos campos, validações de tamanho, obrigatoriedade de campos, fluxos alternativos de autenticação também)

**Comment by luanaflorencio** [comment]
Link para o Protótipo:
https://www.figma.com/file/fXqKMjmdJT3MfUUPOHNMnl/Prot%C3%B3tipo-Econ%C3%B4mico?node-id=0%3A1
