### ISSUE TITLE
Criação do modelo de banco de dados

### ISSUE THREAD

**Issue by lilialnas** [luanaflorencio/economico#4]
Eu como desenvolvedor quero criar o modelo de dados para definir as entidades do sistema.

**Comment by luanaflorencio** [comment]
![bd](https://user-images.githubusercontent.com/49694340/104775274-d5297500-5756-11eb-9926-6df40712f8f6.png)

**Comment by luanaflorencio** [comment]
![banco-eco](https://user-images.githubusercontent.com/49694340/105064989-2178fb80-5a5c-11eb-86d0-a17a069d4857.png)

**Comment by luanaflorencio** [comment]
![bd](https://user-images.githubusercontent.com/49694340/105115525-b8b77080-5aa7-11eb-9a6f-5470e912ad67.png)
